### ISSUE TITLE
Unsafe argument of type `any` on `PlatformProviderResponse.data`

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#1013]
When using the `PlatformProviderResponse` type, accessing the `data` property nets ye olde complainte:

> Unsafe argument of type `any` assigned to a parameter of type `object`.

Here's the line that actually calls the `data` property: https://github.com/PhilanthropyDataCommons/front-end/blob/3e39eb2f5815dd0de2caf03733d94242475465ef/src/components/DataPlatformProvider/DataPlatformProviderLoader.tsx#L190

Unsure if this should be part of https://github.com/PhilanthropyDataCommons/service/issues/1004 or is separate.

**Comment by slifty** [comment]
Part of the issue here is that it basically *is* an `any` due to the nature of our partial implementation of platform provider data.

I think for this one you should just use a lint disable, and we know we'll be refactoring this functionality / properly implementing it down the line.

**Comment by reefdog** [comment]
Perfectly fine by me.

**Comment by reefdog** [comment]
I should close this with the appropriate status!

**Comment by reefdog** [comment]
@slifty 😮 how do you get credit for closing this as not planned? I thought I did that! Here, I'm gonna steal credit.

**Comment by reefdog** [comment]
Ohhh, I see now. I changed the drop-down to "Close as not planned" but didn't actually click the Close button. I didn't realize it was a two-step.

This was useful for more than just narcissism.

**Comment by reefdog** [comment]
@slifty discovered that swagger-codegen incorrectly translates `object` to `any`, a problem subsequently [fixed](https://github.com/OpenAPITools/openapi-generator/commit/9368bea130c1bc5a0d039e228954c3e66ce89cc1) in the [swagger-codegen](https://github.com/swagger-api/swagger-codegen) fork [openapi-generator](https://github.com/OpenAPITools/openapi-generator).

Thus, we can actually reopen this issue and consider it blocked until either swagger-codegen is fixed or we [move to openapi-generator for SDK generation](https://github.com/PhilanthropyDataCommons/sdk/issues/25).

**Comment by slifty** [comment]
I believe this is now fixed (we moved to the openapi generator)
