### ISSUE TITLE
Make base fields and application forms from spreadsheets

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#102]
There are several aspects:
* A semi-automated workflow to take spreadsheets and make JSON canonical fields from the data.
* A draft of canonical fields from the spreadsheets given so far.
* Notes of potential issues or conflicts along the way.

**Comment by bickelj** [comment]
I updated test and prod with the slightly better versions of auto-generated shortCode and applicationForm.

**Comment by bickelj** [comment]
This script gets it part of the way there (no special handling for quote characters, inefficient, fails lint, etc.):
```TypeScript
import fs from 'fs';
import CsvReadableStream from 'csv-reader';

const psvInput = fs.createReadStream('file.psv', 'utf8');

console.log('insert into canonical_fields (id, label, short_code, data_type, created_at) overriding system value values')
let firstRowArrived = false;
psvInput.pipe(
  new CsvReadableStream({
    parseNumbers: true,
    parseBooleans: true,
    trim: true,
    delimiter: '|',
    asObject: true,
  }),
).on('data', (row: any) => {
  if (firstRowArrived) {
    console.log(`,(${row.id}, '${row.label}', '${row.shortCode}', '${row.dataType}', '${row.createdAt}' )`);
  }
  else {
    console.log(`(${row.id}, '${row.label}', '${row.shortCode}', '${row.dataType}', '${row.createdAt}' )`);
  }
  console.error('A row arrived: ', row);
  firstRowArrived = true;
}).on('end', () => {
  console.error('No more rows!');
  console.log(';');
});
```

**Comment by bickelj** [comment]
I updated the script to be a little more complete.
<details>
<summary>Updated script</summary>
```TypeScript
import fs, { WriteStream } from 'fs';
import os from 'os';
import CsvReadableStream from 'csv-reader';
import { parse } from 'ts-command-line-args';

interface Args {
  inputFile: string;
  outputFile: string;
}

const args = parse<Args>({
  inputFile: String,
  outputFile: String,
});

const psvInput = fs.createReadStream(args.inputFile, 'utf8');
const sqlOutput = fs.createWriteStream(args.outputFile, 'utf8');

sqlOutput.write(`INSERT INTO canonical_fields (id, label, short_code, data_type, created_at) OVERRIDING SYSTEM VALUE VALUES${os.EOL}`);

let firstRowArrived = false;
psvInput.pipe(
  new CsvReadableStream({
    parseNumbers: true,
    parseBooleans: true,
    trim: true,
    delimiter: '|',
    asObject: true,
  }),
).on('data', (row: any) => {
  const label = row.label.replace('\'', '\'\'');
  const shortCode = row.shortCode.replace('\'', '\'\'');
  const dataType = row.dataType.replace('\'', '\'\'');
  const createdAt = row.createdAt.replace('\'', '\'\'');
  if (firstRowArrived) {
    sqlOutput.write(`,${os.EOL}(${row.id}, '${label}', '${shortCode}', '${dataType}', '${createdAt}')`);
  }
  else {
    sqlOutput.write(`(${row.id}, '${label}', '${shortCode}', '${dataType}', '${createdAt}')`);
  }
  firstRowArrived = true;
}).on('end', () => {
  sqlOutput.write(`;${os.EOL}`);
  sqlOutput.close();
});
```
</details>

**Comment by bickelj** [comment]
I created https://github.com/PhilanthropyDataCommons/data-scripts to house the scripts used to generate what you see in service PR #164.

**Comment by bickelj** [comment]
There are two scripts in https://github.com/PhilanthropyDataCommons/data-scripts/tree/main/src that transform spreadsheet data to JSON and SQL respectively. There is a new spreadsheet format so those scripts need to be adapted or replaced with scripts that process the newer sheet. The resulting SQL file will be used to seed canonical fields in the service software, e.g. #164.

**Comment by bickelj** [comment]
Comments on #305 and #309 as well as #282, #283, #285, #297 #298, #299, and especially #104 and its ilk all indicate that the third-generation base fields spreadsheet is also lacking. It makes an assumption of one-field-to-one-field for the purpose of getting data into PDC, but that assumption is not correct. There needs to be a way to formally map one-to-many and many-to-one fields in whatever base field generation process we use.

**Comment by slifty** [comment]
This is something that we can close out for now -- our current implementation plan for phase 2 essentially separates the process of data entry from base field creation.  In future phases we may well have a more robust data entry interface that supports the creation of new fields / field mappings from CSV uploads.
