### ISSUE TITLE
openapi descrepency

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#110]
Problem: Using the generated client from the openapi.json - the application forms post fails with error "missingProperty":"canonicalFieldId"

The application form field requires the canonical field short code - not the canonical field id.

In openapi.json - "ApplicationFormField" properties specifies "canonicalFieldShortCode" but the required list has "canonicalFieldId"

**Comment by bickelj** [comment]
Thank you for finding this!

**Comment by slifty** [comment]
Ah thank you!  This was an accident from a change from short code to ID for this endpoint.

Opening a PR now with a fix.
