### ISSUE TITLE
Update `users` table to use natural key

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#1155]
Right now we exclusively use synthetic keys (an `id` column with auto increment) across all of our tables.

@jasonaowen has raised the idea of moving to use natural keys when there is a candidate.  We are having a deeper discussion about this over in #1141 for `base_fields` but as I'm about to improve our `users` table I wanted to raise it here as well.

`users` has an `account_id` column which is required, unique, guid that is generated by an authentication system.  At this point it is a reasonable natural key, and I believe since it's a guid it is decoupled from keycloak (e.g. if we added other auth systems it would still be a valid natural key).

It won't change, it's required, and it's unique -- a solid natural key candidate!

Let's update `users` to ditch our synthetic ID.

This will simplify the work of #1154 since we'll only need to create a `PUT` endpoint.
It will also mean that our clients will be able to avoid looking up a user ID from our system if they know how to parse an `accountId` from a jwt.

**Comment by bickelj** [comment]
@slifty I'm OK with it.

**Comment by slifty** [comment]
Since opening this issue at some point I spoke with @jasonaowen about the topic and he suggested we consider being even more specific to what `accountId` is.

In particular: it's a keycloak ID / UUID.

I originally was concerned that we would be coupling too closely with Keycloak and might not be able to support other auth services, but he pointed out that Keycloak SHOULD be the thing we integrate with, and that it can handle integration with other services directly.

To that end, I'd like to propose we rename it to `keycloak_id` while also making it a natural key (and then setting the column type to UUID so we can have db validation of the values).
