### ISSUE TITLE
API Key failing

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#118]
Using the API key was always returning 401 unauthorized. Tracing code found in apiKeyChecker.ts line 22
if (validApiKeys.includes(apiKey.toString())) { 

was always returning false even though the key matched. Changing to: 

if (validApiKeys.toString().includes(apiKey.toString())) { 

worked

**Comment by bickelj** [comment]
Thank you for reporting this issue.

I suppose the software expects a keys file with Unix-style line endings. I wonder if there are carriage returns in the keys file. If on Windows, perhaps use Notepad++ to see and change it (Edit -> EOL Conversion).

**Comment by bickelj** [comment]
@mortimal1 Did this suggestion help?

**Comment by mortimal1** [comment]
yes, that worked - thank you. Could you have used os.EOL instead of hard coding '\n'?

**Comment by bickelj** [comment]
@mortimal1 Great suggestion, done in #123.
