### ISSUE TITLE
GET /applicants by externalId not working

### ISSUE THREAD

**Issue by mortimal1** [PhilanthropyDataCommons/service#121]
Has the /applicants/{externalId } endpoint been implemented yet?

**Comment by slifty** [comment]
It has not been implemented yet, but it is one of the next items on our roadmap.

**Comment by bickelj** [comment]
This came up again recently and it needs to be fixed.

**Comment by bickelj** [comment]
I have a local branch with a draft of this change but it has not been tested yet.

**Comment by bickelj** [comment]
@mortimal1 There is a new approach to modeling organizations/applicants. [See also this comment in the associated fix attempt](https://github.com/PhilanthropyDataCommons/service/pull/315#issuecomment-2077649280).
