### ISSUE TITLE
Track related data standards; use them where appropriate.

### ISSUE THREAD

**Issue by kfogel** [PhilanthropyDataCommons/service#122]
I'm not sure how the project should best make use of these data standards at this stage, but let's start by keeping track of them.  Here are some that we should be aware of (and someday perhaps support at least as import/export formats):

* [360Giving Data Standard](https://www.threesixtygiving.org/data-standard/)
* [Philanthropy Classification System](https://taxonomy.candid.org/)
* [Common Approach to Impact Measurement](https://www.commonapproach.org/) (see "Standards" tab)
* [Impact Genome](https://impactgenome.org/)
* [Common Data Model for Nonprofits (Micosoft)](https://github.com/microsoft/Industry-Accelerator-Nonprofit)
* [International Aid Transparency Initiative](https://iatistandard.org/en/)

(Some of the above come from the [Social Impact Data Standards spreadsheet](https://docs.google.com/spreadsheets/d/1BzrAYHIjTtYI7TTFR0Rp9QavvPPKCPOjcnO50uRvotE/edit#gid=0), which may have other entries of interest.)

**Comment by slifty** [comment]
I'm closing this as stale for now *BUT* I'm going to cross reference #561 in case these links come in handy as we reflect on our current list of base fields.
