### ISSUE TITLE
Create test cases for the data conflict scenarios identified in #1176

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#1257]
In #1176 @bickelj laid out a bunch of specific scenarios for conflict resolution which are essentially functional specifications for how our data resolution logic should work when retrieving an organization.

Next step is to convert these scenarios into tests (and of course make sure the tests pass)

**Comment by bickelj** [comment]
While making more tests in #1262 and looking at the scenarios in #1176, I realized that the example scenarios in #1176 were either examples or ambitious examples. In other words, we have no capability of asking the web about an IRS EIN, for example, so integrating to that is currently not a thing. Unless we want it to be, in which case we have to build that capability.

**Comment by slifty** [comment]
I believe this is now complete
