### ISSUE TITLE
Create a CHANGEMAKER_DATA.md file in `/docs`

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#1274]
This should document the intent of the current logic (the scenarios) and should also note some of the known "edge cases" / potential limitations of our current logic.

**Comment by bickelj** [comment]
I should have read the OP here, but is it essential to include the scenarios or the edge cases? The doc as I wrote it briefly describes how to use the `/changemakers` endpoint and includes details of how the heuristic currently works.

**Comment by bickelj** [comment]
Aside or GitHub gripe: why don't Project status transitions appear directly in the feed? Maybe in another 10 years GitHub will reach feature parity with Redmine.

**Comment by bickelj** [comment]
I named it `/docs/CHANGEMAKER_DATA.md` because it is specifically about changemakers.
