### ISSUE TITLE
Deployment failure 2024-12-03

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#1356]
This issue is to investigate a notification about a DO deployment failure last night, December 3.

**Comment by bickelj** [comment]
First, there were two notifications, one for the test environment and one for the prod environment. I would prefer that deployment to prod be conditioned on successful deployment to test. Thankfully in this case it is likely the same error preventing both.

**Comment by bickelj** [comment]
Screenshots in order found from the email link for the test environment deployment:

![Screenshot 2024-12-04 at 09-37-55 pdc-service-test - DigitalOcean App Platform](https://github.com/user-attachments/assets/87753417-fed2-415e-bdb5-9a0e9e8b603a)

![Screenshot 2024-12-04 at 09-39-17 pdc-service-test - DigitalOcean App Platform](https://github.com/user-attachments/assets/8e7b2ede-d946-4ffb-ac9b-46039df070f7)

![Screenshot 2024-12-04 at 09-39-55 pdc-service-test - DigitalOcean App Platform](https://github.com/user-attachments/assets/bf0458ee-7b33-4089-b108-e3b8fc3a872a)






Prod looks the same, example image from the production environment:

![Screenshot 2024-12-04 at 09-45-40 pdc-service-test - DigitalOcean App Platform](https://github.com/user-attachments/assets/5779796a-e895-433c-a6d7-f28583063a50)

**Comment by bickelj** [comment]
The timing correlates with the merge of https://github.com/PhilanthropyDataCommons/service/pull/321. For a moment I was wondering if there was a merge at this time at all, but then I found one.

**Comment by bickelj** [comment]
I see that DO rolled back to the previous version and the service is up and working, so this is not an immediate issue, only a high priority issue:

![Screenshot 2024-12-04 at 09-52-02 pdc-service-prod - DigitalOcean App Platform](https://github.com/user-attachments/assets/24df33bd-db04-41ad-965f-570c7d5069a7)

It's not clear what went wrong from this initial investigation.

@jasonaowen Would you mind taking a look? You set up the DO deployments and also merged the relevant PR so I bet you'll be able to find the issue more quickly than I can.

**Comment by jasonaowen** [comment]
I believe the problem was caused by the addition of `requirements.txt`, which makes DOAP interpret it as a Python project. I'm looking into how to either specify the desired buildpacks, or use a different filename and tell dependabot that it is in fact a `requirements.txt` file it can maintain.

**Comment by jasonaowen** [comment]
The merge commit for #1359 successfully deployed to the [test](https://cloud.digitalocean.com/apps/21057031-b8f6-4acd-a82a-912e2607e7e7/deployments/328fe27e-394b-46eb-ab98-04a441de87d5?i=866d2e) and [prod](https://cloud.digitalocean.com/apps/b7ad59b2-c982-4d32-b0e5-d328defa4051/deployments/bce943bf-6bd8-4f00-8049-94374f82b803?i=866d2e) apps.

Thanks for flagging this, @bickelj!

**Comment by bickelj** [comment]
@jasonaowen Thanks for the quick investigation and fix!
