### ISSUE TITLE
Validate GitHub Actions workflow files

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#1375]
The YAML files in `.github/workflows` need to be correctly shaped for workflows to run, but it's not obvious to me when or how they checked by GitHub Actions itself. Finding incorrect syntax - and, hopefully, suggesting corrected syntax - is something that should at least be checked on pull requests, and ideally be easily checkable locally.

I found a few options so far, but none of them are perfect:

- [action-validator](https://github.com/mpalmer/action-validator) has an NPM package, but the CLI only does one file at a time, and does not handle globs; we'd have to write some kind of wrapper script.
- action-validator gets its schema from [schemastore](https://github.com/SchemaStore/schemastore) (https://json.schemastore.org/github-workflow.json) which could be used with [ajv-cli](https://ajv.js.org/guide/environments.html#command-line-interface). ajv-cli does accept globs, but we'd either have to download the schema locally, vendor it, or add schemastore as a git submodule.
- [actionlint](https://github.com/rhysd/actionlint) seems to be the most thorough, can be run locally, and has its own [GitHub Action](https://github.com/marketplace/actions/actionlint) to make adding it to CI easy, but it's written in Go, so that'd be yet another language dependency; folks would either need to download the binary or have Go installed to compile it locally.

We could also just not do this, since we don't update our actions all that often, but I found it helpful to have some validation while working on PR #1374.

Thoughts, @bickelj @hminsky2002 @slifty?

**Comment by slifty** [comment]
@jasonaowen I'll take a closer look at this shortly but in the meantime: when you open a PR I believe GitHub runs the actions defined in the branch, so for most of our actions would that be enough?

I agree that for scheduled actions that doesn't quite do the trick.

**Comment by jasonaowen** [comment]
Now that I look more closely, actioncheck actually does [a lot](https://github.com/rhysd/actionlint/blob/v1.7.4/docs/checks.md) more than just validating the YAML, including shellcheck for `run:` steps and hardcoded credentials, and is what I'd advocate.

**Comment by bickelj** [comment]
@jasonaowen I say we try one, no objection to the one you mentioned, actionlint. If it helps, keep using it. If it causes pain, find an alternative or stop using it. A [while ago I found act](https://github.com/PhilanthropyDataCommons/deploy/pull/107#issuecomment-2023430265) to be helpful when developing GH actions.

**Comment by slifty** [comment]
This is resolved by #1379 right?

**Comment by jasonaowen** [comment]
Oops yes, I meant to have a `Resolves` in the PR! Thanks.
