### ISSUE TITLE
Add an `externalId` for ApplicationsForms and ApplicationFormFields

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#227]
We want to make it easy for a third party to map their application forms to the versions stored in the PDC.

This will require us to add `externalId` to both the Application Form *and* the Application Form Field.

**Comment by bickelj** [comment]
An alternative that does not require adding columns: use the canonical spreadsheet (or a subset) in CSV form to map these outside the software, e.g. in `data-scripts` repository.

**Comment by bickelj** [comment]
Adding `externalId` will be useful, though.

**Comment by bickelj** [comment]
The reason for addressing this now is it came up with regard to data ingest, e.g. from spreadsheets in #102.

**Comment by bickelj** [comment]
See [comments in the PR](https://github.com/PhilanthropyDataCommons/service/pull/264), either moot or not needed. @slifty if you disagree and think this is still needed, please re-open and clarify.
