### ISSUE TITLE
Add authorization

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#255]
Once we have the ability for users of our API to authenticate - that is, once the API can validate that a known user (human or machine) is making a given request - we need the ability for our API to reject access to specific endpoints depending on the role of that authenticated user.

This issue is split out of #96, and specifically handles authorization once authentication is sorted out.

Note that the situation is somewhat complicated in that we have both individual humans and organizational partners, and the latter will most likely be granted [client credentials](https://oauth.net/2/grant-types/client-credentials/) that will be allowed to have some level of access.

We will need to decide:
- what roles do we want?
- what client-specific permissions do we want?
- what endpoints need access controls?

Once we have answers to those questions, configure Keycloak and update the API accordingly.

(There is the related operational question of "who should be granted access to which roles?" We would ideally answer that question in the same discussions, but may not need to document the resulting policy here, and do not need to block implementation on having an answer.)

**Comment by jasonaowen** [comment]
We discussed this during the team meeting today (including with @slifty, @bickelj, @kfogel, and @jim-mcgowan).

For the March MVP, we will defer authorization - if you can get a token from Keycloak (either by signing in or with client credentials), you will have full access to the API. This will be mitigated by having a small, trusted community, and with communication and community norms.

@kfogel and @jim-mcgowan will come up with the long-term access control goals, document them here, and prioritize them against other work (possibly breaking up those goals into multiple steps, as needed).

(Does that match everyone's understanding of what we discussed?)

**Comment by kfogel** [comment]
> (Does that match everyone's understanding of what we discussed?)

Yes.

**Comment by jasonaowen** [comment]
You all understand the data model better than I do, but in case having a reference of the authentication/authorization data model and some of our capabilities is helpful:

- a *subject* is a known, authenticated, named human: they can log in to Keycloak, and can get a token to prove it to the API. (Keycloak uses "user", but I feel like we've had some confusion in our discussions when using that word, so I'll use the term encoded in the token)
- a *client* is an application that can either access the API on behalf of a user (as with the data-viewer), or directly on its own behalf. Clients are defined in Keycloak and have a client ID.
- a *token* or [JWT](https://en.wikipedia.org/wiki/JSON_Web_Token) is issued by Keycloak, and used to authenticate to the API. It encodes the client that requested it, and - if the request was on behalf of a person - the subject and their claims.
- a subject may have one or more *[roles](https://www.keycloak.org/docs/latest/server_admin/#assigning-permissions-using-roles-and-groups)* - these roles are defined and assigned in Keycloak. Keycloak can use roles to limit a subject's access to clients, and/or Keycloak can encode these into a subject's tokens as *claims*. Keycloak does not attach any semantic meaning to such claims; that's up to code we will have to write in the API. Assigning these roles to subjects may be automated, but I believe it is generally best practice to limit the number of roles - that is, I don't think we want to automatically create a role in Keycloak for every individual access grant, but we *should* create roles for defined groups of people.

I'll also mention the Wikipedia article on [access control](https://en.wikipedia.org/wiki/Computer_access_control#Access_controls), which has a good survey of the available models. From earlier conversations, it sounds like we'll want a combination of discretionary and role-based access controls.

There's one endpoint that I think we want to make publicly accessible: retrieving the list of canonical fields. That'll allow easy import to new instances, as discussed in https://github.com/PhilanthropyDataCommons/service/pull/164#issuecomment-1468841107.

**Comment by kfogel** [comment]
*Thank you*, Jason -- that is a very helpful vocabulary-and-concept stabilizer to have at hand.

**Comment by kfogel** [comment]
Update: we probably won't do access controls in this pilot phase.  This ticket should stay open; I'm just letting you know that it may stay open for a while -- until we get to the stage of designing and implementing this feature!

**Comment by jasonaowen** [comment]
One small decision is that we want the `/baseFields` endpoint to be publicly readable, without authentication or authorization. (See also the related [discussion on Zulip](https://chat.opentechstrategies.com/#narrow/stream/75-PDC/topic/base.20fields/near/164653).)

**Comment by bickelj** [comment]
TODO: this needs to be broken down more, currently it's kind of synonymous with an overarching theme/milestone/thing seen at https://github.com/orgs/PhilanthropyDataCommons/projects/3/views/6
