### ISSUE TITLE
SVG versions of PDC logo

### ISSUE THREAD

**Issue by jim-mcgowan** [PhilanthropyDataCommons/service#269]
Attached are SVG versions of the Philanthropy Data Commons logo provided by Jonathan Mergy.

![PDC Logo - White](https://user-images.githubusercontent.com/4147733/226970578-91e93903-b490-4237-9445-8708a6bd0bf9.svg)
![PDC Logo Icon - White](https://user-images.githubusercontent.com/4147733/226970582-69026575-de4d-496b-8818-c80543885367.svg)
![PDC Logo Icon](https://user-images.githubusercontent.com/4147733/226970587-c4152dd9-f800-4820-bf19-2e48ca2e6efb.svg)
![PDC Logo](https://user-images.githubusercontent.com/4147733/226970589-e81b8d84-f579-43d3-8a29-2e8b13bcdd66.svg)
![PDC-Stacked](https://user-images.githubusercontent.com/4147733/226970590-0a5e059c-4949-4f2e-9143-1c430ece50fa.svg)

**Comment by jmergy** [comment]
Thanks @jim-mcgowan

**Comment by slifty** [comment]
I believe these are now in use

**Comment by reefdog** [comment]
@slifty We actually still don't have "true" SVG originals of the logomark, just raster → vector conversions. But it's fine to close this, we have another issue (https://github.com/PhilanthropyDataCommons/meta/issues/129) tracking that.
