### ISSUE TITLE
Explore use of dictionary objects instead of a field array when returning proposal versions.

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#276]
Our deep object representation of proposal version returns an array of "proposalFieldValues" which basically is a key value pair between form fields and responses.  This is unwieldy for API clients because accessing any given field value becomes an O(n) operation / they need to iterate through the entire list.

There would be real value in providing a dictionary object instead, using swagger's `additionalProperties` object feature.

The concern is making sure consumers of the swagger spec are able to reliably access those values.

**Comment by jasonaowen** [comment]
I just realized that I had misunderstood the data model during that conversation!

I was advocating for representing the data with an object, using the canonical field short codes as the keys. One of my arguments in support was that it communicates to the user that the values are unique, but I don't think they are - the *positions* are unique, but application forms can have the same fields in different positions, and proposal values can have multiple answers to a given field in different positions.

If there are other aspects of our data model where we can communicate uniqueness with objects, we should, and then it will be good to validate this approach. However, I think for now the priority on this has dropped.

**Comment by slifty** [comment]
Ah right yeah -- when we were talking about this I was forgetting that fact (though we could still have each short code point to an array of objects).

**Comment by jasonaowen** [comment]
> (though we could still have each short code point to an array of objects).

I think that'd sacrifice the position data, unfortunately, and that's probably more important. For now, I'm just using [`Array.prototype.find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).

**Comment by slifty** [comment]
I'm going to mark this as stale / wontfix for now, though obviously in future we might find ourselves adjusting the API as the schema is updated.
