### ISSUE TITLE
Normalize and validate phone numbers

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#283]
We have several phone number fields: `organization_phone`, `proposal_primary_contact_phone`, `proposal_submitter_phone`, and `proposal_submitter_mobile_phone`. We should use something like [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js) to validate the data assigned to any of these fields - and reject invalid or unparseable values - and normalize it before storing it in the database.

**Comment by jasonaowen** [comment]
This came up by reviewing recently imported data, and seeing an entry like:

> Proposal Primary Contact Phone: `Full Name Tel: (555) 555-5555 name@example.com`

It's much easier to find and fix such errors when they are rejected immediately, instead of requiring post-import review.

**Comment by reefdog** [comment]
@kfogel has asked that the Data Viewer display the phone number's country code, and that we format the phone number consistently and correctly (where a standard exists) for each country. He's comfortable with us assuming a phone number is US in the current iteration.

As implied by this issue, the correct place for this is in the PDC. The Data Viewer should, at most, format the phone number, but IMO should not be responsible for adding a country code.

**Comment by jasonaowen** [comment]
I think those are two separate concerns! The API should validate and store the phone number in some normalized form (like `+15435551234` or so), and the front end should format that nicely (like `(543) 555-1234` or so).

**Comment by reefdog** [comment]
Agreed!

**Comment by slifty** [comment]
Since this issue was created we *do* validate phone number.  That said, we are currently explicitly NOT normalizing data in our system.  This may chance, but I think it would be appropriate to mark this issue as completed until that point.

When data normalization gets thought through more robustly (see #1087) we will certainly create a series of new issues for various normalization tasks.
