### ISSUE TITLE
Post proposals specification is incomplete

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#286]
https://api.philanthropydatacommons.org/#/Proposals/post_proposals

I don't believe this "request body" is properly populated right now -- in particular it doesn't document anything about accepting field values.

**Comment by bickelj** [comment]
The field values currently go into /proposalVersions so I think it's OK.

**Comment by slifty** [comment]
You're right!  I'm going to mark this as closed.

To be clear for anybody who finds this, the process is:

POST to create a new proposal
POST to create a proposal version
