### ISSUE TITLE
Search by state

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#289]
Once we have search implemented (#277), we want to specifically support the use case of geosearch. We expect the most common search to be by US state, such as "find proposals from organizations headquartered in Florida".

This will be our first bit of faceted search, and will depend on how we store address data (#104).

**Comment by slifty** [comment]
This feature may well be useful at some point, but it seems that it's not a priority for this phase.  Until there's a direct user need for it (and a path to implementation) I think we can close this.
