### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#298]
Validate that base fields that store email addresses, such as `organization_email` or `proposal_primary_contact_email`, have values with well formed email addresses, suitable for putting into the template `<a href="mailto:{}">{}</a>`.

Parsing email addresses is a famously hard problem, and the only way to truly determine if an email address is valid is to send an email to it, but I'm not proposing we do anything like that. Instead, do a basic check that the address looks well-formed, so as to make sure there is no extraneous data like `Full Name <fullname@example.com>` - we'd only want the `fullname@example.com` value in that example.

**Comment by bickelj** [comment]
Resolved in #925.
