### ISSUE TITLE
Set up CI / CD

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#3]
We need to set up deployment for this repo (and CI / tests / etc.)

Part of doing this will be deciding on Docker vs server deployment, etc.

**Comment by bickelj** [comment]
With a combination of PR #10 and PR #13 and a .conf file change, with the exact image id used, the proxy server reaches the express server just fine.
```
$ docker compose -f compose.yml up -d
[+] Running 4/4
 ⠿ Network deploy_default            Created                                                                                                                                               0.1s
 ⠿ Container deploy-reverse-proxy-1  Started                                                                                                                                               1.2s
 ⠿ Container deploy-web-1            Started                                                                                                                                               1.4s
 ⠿ Container deploy-database-1       Started
$ docker ps
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS        PORTS                                                                            NAMES
d709d7461497   bitnami/postgresql:14.4.0-debian-11-r1   "/opt/bitnami/script…"   3 seconds ago   Up 1 second   5432/tcp                                                                         deploy-database-1
1a7c073c402c   07254019df1f                             "npm start"              3 seconds ago   Up 1 second   3000/tcp                                                                         deploy-web-1
dc888a8fb244   bitnami/nginx:1.22.0-debian-11-r8        "/opt/bitnami/script…"   3 seconds ago   Up 1 second   0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   deploy-reverse-proxy-1
$ docker logs deploy-reverse-proxy-1
nginx 21:27:15.35 
nginx 21:27:15.35 Welcome to the Bitnami nginx container
nginx 21:27:15.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
nginx 21:27:15.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
nginx 21:27:15.35 
nginx 21:27:15.36 INFO  ==> ** Starting NGINX setup **
nginx 21:27:15.37 INFO  ==> Validating settings in NGINX_* env vars
nginx 21:27:15.38 INFO  ==> No custom scripts in /docker-entrypoint-initdb.d
nginx 21:27:15.38 INFO  ==> Initializing NGINX
realpath: /bitnami/nginx/conf/vhosts: No such file or directory

nginx 21:27:15.40 INFO  ==> ** NGINX setup finished! **
nginx 21:27:15.41 INFO  ==> ** Starting NGINX **
$ docker logs deploy-web-1

> @pdc/service@0.0.0 start
> node .

Server running on localhost:3000
$ curl -vvv localhost:80
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 23 Jun 2022 21:27:41 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 13
< Connection: keep-alive
< X-Powered-By: Express
< ETag: W/"d-lDpwLQbzRZmu4fjajvn3KWAx1pk"
< X-Frame-Options: SAMEORIGIN
< 
* Connection #0 to host localhost left intact
Hello, world!
```

**Comment by bickelj** [comment]
At present, there is no intermediate node module publication but I suppose that can be added.

**Comment by bickelj** [comment]
Docker images are now being built on every merge to main and pushed to the GitHub Container Registry, see PR #14 and https://github.com/PhilanthropyDataCommons/service/pkgs/container/service

**Comment by bickelj** [comment]
However, these images are not yet publicly available, they are private by default.

**Comment by bickelj** [comment]
See https://github.com/PhilanthropyDataCommons/deploy/issues/7 where there is now an action/workflow to update the compose script based on a given tag. The action/workflow that has this context will be the [build action of this repository](https://github.com/PhilanthropyDataCommons/service/actions/workflows/build.yml), the service repository. This is kind of awkward because it's the tail wagging the dog. I would rather have the [deploy project](https://github.com/PhilanthropyDataCommons/deploy) watch for the new images in the [service project](https://github.com/PhilanthropyDataCommons/service) than have the service project be aware of a top-level/outside/optional project.

**Comment by bickelj** [comment]
It looks like that last failure was either a temporary hiccup on the registry side or a one-time bootstrapping issue because this last merge to main had a successful build/push/tag/tag-as-latest: https://github.com/PhilanthropyDataCommons/service/runs/7236836402?check_suite_focus=true

**Comment by bickelj** [comment]
I tried a manual deployment on the test server using `deploy.sh` from the `deploy` project and had this result:
```
$ ./deploy.sh 
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
Pulling reverse-proxy ... done
Pulling web           ... error
Pulling database      ... done

ERROR: for web  Head "https://ghcr.io/v2/philanthropydatacommons/service/manifests/20220708-62920b0": unauthorized
ERROR: Head "https://ghcr.io/v2/philanthropydatacommons/service/manifests/20220708-62920b0": unauthorized
```
So I created #28 for this issue.

**Comment by bickelj** [comment]
The current blockers for deployment are:
* Pulling images: #28 (or setting up credentials on the test and prod servers to do `docker login` yuck)
* Adding commonly-trusted certificates: https://github.com/PhilanthropyDataCommons/deploy/issues/2, depends on the next item
* Domain names: https://github.com/PhilanthropyDataCommons/deploy/issues/23
* Limiting access (or accepting the risk of) the build user eyes-open.

**Comment by bickelj** [comment]
#28 is resolved, it raises a new issue when I try to pull locally, but I created #39 for it:
> latest: Pulling from philanthropydatacommons/service
> no matching manifest for linux/amd64 in the manifest list entries
The next two issues of TLS and domain names have items in the deploy project. The last one can fall under https://github.com/PhilanthropyDataCommons/deploy/issues/9.

In other words, the bulk of the CI tooling is in place for this project, via various tickets and this one, and the rest is tracked in other tickets, so we can call this initial set up of CI / CD done.
