### ISSUE TITLE
Implement `GET /opportunities` endpoint

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#31]
This endpoint should return all registered opportunities in the system.

**Comment by bickelj** [comment]
It seems like #46 would be helpful prior to adding this, maybe not strictly required.

**Comment by slifty** [comment]
Yes for sure -- I'll get that merged in ASAP

**Comment by bickelj** [comment]
Wow, this worked:
```
async function getOpportunities(req: Request, res: Response):Promise<void> {
  const opportunities: Result<Opportunity[]> =
      await db.sql<Opportunity[]>('selectAllOpportunities');
  res.status(200)
    .contentType('application/json')
    .send(opportunities.rows);
}
```

**Comment by bickelj** [comment]
I get the same exact result when using this instead, so there is no magic in the additional type information:
```
async function getOpportunities(req: Request, res: Response):Promise<void> {
  const opportunities = await db.sql('selectAllOpportunities');
  res.status(200)
    .contentType('application/json')
    .send(opportunities.rows);
}
```

**Comment by bickelj** [comment]
The type info does seem useful though. As far as not getting an integer when it is a bigint, it looks like that's some weirdness with the node pg-types library and/or JavaScript itself. I see this nugget at https://github.com/brianc/node-pg-types/

> Let's do something I commonly like to do on projects: return 64-bit integers (int8) as JavaScript integers. Because JavaScript doesn't have support for 64-bit integers node-postgres cannot confidently parse int8 data type results as numbers because if you have a huge number it will overflow and the result you'd get back from node-postgres would not be the result in the database. That would be a very bad thing so node-postgres just returns int8 results as strings and leaves the parsing up to you.

Oh yeah. JavaScript `number` covers both ints and floats. I guess I had forgotten how weird JavaScript can be.

**Comment by bickelj** [comment]
So treating it like a string in JSON is appropriate, I suppose.

**Comment by bickelj** [comment]
There are some interesting possibilities with https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-CREATION-TABLE but first we should get the straighter-forward thing working.

**Comment by bickelj** [comment]
Done in PR #66
