### ISSUE TITLE
Explore other openapi validation tools

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#318]
> Thanks for the warning regarding the online server use. I thought I would recommend [redocly](https://www.npmjs.com/package/@redocly/cli) (from [openapi.tools](https://openapi.tools/#description-validators)) but when I ran it it gave like 25 more errors on this branch. I suppose if those are substantial (i.e. a generator won't work) then we should switch. In any case, this is certainly an improvement.

_Originally posted by @bickelj in https://github.com/PhilanthropyDataCommons/service/pull/317#discussion_r1180629083_

**Comment by bickelj** [comment]
If I recall correctly, the validator we used gave us the right amount of feedback to get the spec into shape such that a client could be generated from it, so I am withdrawing my suggestion for now. We are probably fine for the time being. If we hear otherwise, reopen or open new.
