### ISSUE TITLE
Use real URLs in our swagger specification

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#319]
> We probably will want to serve up the actual, final openAPI spec in production rather than pointing folks to the git repo.

_Originally posted by @bickelj in https://github.com/PhilanthropyDataCommons/service/pull/317#discussion_r1180630780_

**Comment by bickelj** [comment]
This came up again today. For folks generating a client this would help.

**Comment by slifty** [comment]
It's unclear if this is resolved BUT it's likely to come to a head as part of https://github.com/PhilanthropyDataCommons/sdk/issues/2

**Comment by slifty** [comment]
... I believe this is resolved (we overwrite our `authorizationUrl` etc in the [documentationRouter](https://github.com/PhilanthropyDataCommons/service/blob/main/src/routers/documentationRouter.ts).

If that isn't the case we can re-open with more detail.
