### ISSUE TITLE
Workflow dispatch intermittently not working

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#347]
Odd that sometimes the workflow task to notify the deploy project works and sometimes it does not. Earlier this morning it succeeded with https://github.com/PhilanthropyDataCommons/service/actions/runs/4926285781 but more recently it failed e.g. https://github.com/PhilanthropyDataCommons/service/actions/runs/4928649639/jobs/8807271181

**Comment by bickelj** [comment]
I see a pattern where everybody-but-dependabot succeeds and dependabot fails:

![image](https://github.com/PhilanthropyDataCommons/service/assets/8806433/2366b02e-5ea4-4fcb-a608-e42fc143bbc7)

**Comment by bickelj** [comment]
But it was not always this way. The merge commits used to be attributed to the person who merged and the build would succeed:
![image](https://github.com/PhilanthropyDataCommons/service/assets/8806433/1fd5a87a-04e8-4b02-88a9-e484b558f15a)

**Comment by bickelj** [comment]
The last success and first failure appears here:
![image](https://github.com/PhilanthropyDataCommons/service/assets/8806433/6f5956d0-ef10-42b4-a621-c690475c7d97)


So between April 12 around 10 am central and April 18 around noon central is when the change occurred.

**Comment by bickelj** [comment]
There is [this issue comment](https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544) regarding dependabot's inability to access secrets, which makes sense, except dependabot does not merge to main, we do. So if the merge is mistakenly attributed to dependabot that is the issue.

**Comment by jasonaowen** [comment]
Good digging, @bickelj! So no more issuing `@dependabot merge` commands. :white_check_mark:
