### ISSUE TITLE
Implement `POST /applications` endpoint

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#35]
Allows the creation of a new application in the system.

**Comment by bickelj** [comment]
Depends on #64 and #65

**Comment by slifty** [comment]
In working on this I needed to think about how versioning works.  A few pieces on that:

1. An applicant might submit more than one distinct proposal!
2. An applicant might update an existing proposal (create a new version).

To support this I believe we will need to store an "external proposal ID" with a given proposal, so that when the GMS posts the proposal fields our system can manage versioning directly.

**Comment by slifty** [comment]
A parallel question is how will GMSs indicate which field a given value is associated with.

In other conversations we decided that we will not allow clients to talk to us in terms of shortCode; this means they're going to have to look up the application forms, map the short codes themselves, and get our ID.  I think we should stay consistent there (again we may some day decide to provide a quality of life ability to pass a shortCode optionally).  It's also possible that some applications will allow more than one copy of the same canonical field, so this is particularly reasonable to require up front while we're still in prototype mode.

With all that said, for the initial implementation the proposalFieldValues will need the client to pass the `applicationFormFieldId`.

**Comment by bickelj** [comment]
Perhaps the read/GET on one specified entity can return the whole tree of objects for the one requested versus the read/GET for all instances only returns the immediate objects. If that's too inconsistent across the API then maybe an option on the read/GET for one specified entity can return the whole tree of objects. I think for POST we will always want the new instance to have exactly what is needed for that new instance. Those are some of my initial thoughts in response to "A parallel question is how will GMSs indicate which field a given value is associated with."

**Comment by slifty** [comment]
I think that's a great plan (and can be consistent with some of the initial thinking over at https://github.com/PhilanthropyDataCommons/service/issues/101).  And yeah I think that's a fine design rule that we'll want POST to have the correct IDs rather than short codes.

**Comment by slifty** [comment]
I wanted to codify some of the thinking around the POST endpoint here (I'll include it in commits too).

I think our philosophy so far has been to design the first version of these endpoints with a priority towards RESTful design (within reason; note we don't follow this approach for proposalFieldValues for instance).

With that bias in mind, if a GMS wants to create a new version of a proposal they would need to POST to the `proposalVersions` endpoint for a given proposal ID, rather than posting to the `proposals` endpoint.

We may eventually decide to create some quality of life functionality such as:

(A) Allowing a POST to /proposals/{id} to create a new version, or
(B) Implementing a PUT to /proposals that is smart enough to check for an existing application with a given external ID

Again, for now I think it's most clear to just require GMSs check if a proposal exists already with a given externalId and use that ID and then use that ID to post the proposal version.  This means the proposal creation flow would look like this:

1. GET `/proposals?externalId=???` to see if a proposal with the external ID exists already.
2. If not, POST `/proposals` to create one
3. POST to `/proposalVersions` to create a new version of the relevant proposal.

Note that in the final POST, the sent proposal values will be mapped to application field values by the GMS client.
