### ISSUE TITLE
Rename "Proposal" throughout PDC to something else

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#362]
From https://github.com/PhilanthropyDataCommons/service/issues/284#issuecomment-1550676710:

> Note that the majority of applications are not actually proposals; they are simply applicants responding to direct invitations to seek funding. Thus, we would do well to find a better term than proposal.

**Comment by slifty** [comment]
Wanted to associate this with #396 

That said -- this does feel a bit out of scope for now / not a priority for this phase.  If we do end up exploring this I would be curious what GMS's call this concept.

**Comment by bickelj** [comment]
In a meeting today, the participants were OK with still calling the above-mentioned scenario a "proposal."

**Comment by slifty** [comment]
I'll close the issue for now given the above note from @bickelj
