### ISSUE TITLE
`npm run test:ci` prints failures but exits success

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#457]
See https://github.com/PhilanthropyDataCommons/service/actions/runs/5966921283/job/16187534824#step:7:20 and the corresponding "success".

Locally when running `npm run test:ci` I get failures printed but exit 0:
```
$ npm run test:ci

> @pdc/service@0.3.0 test:ci
> jest --config=jest.config.ci.js --runInBand

Determining test suites to run...ts-jest[versions] (WARN) Version 5.1.6 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=4.3.0 <5.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  src/__tests__/proposalVersions.int.test.ts
  ● Test suite failed to run
...
$ echo $?
0
```

**Comment by slifty** [comment]
Unfortunately this is a bug within `ts-jest`: see https://github.com/kulshekhar/ts-jest/issues/4193

**Comment by slifty** [comment]
@jasonaowen pointed out that in the short term we can simply run our tests twice -- once with coverage and once without (coverage is what causes the masked error code).  I'm gonna assign myself to making that change.
