### ISSUE TITLE
mock-jwks no longer supports commonjs

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#458]
From https://www.npmjs.com/package/mock-jwks

> As of version 2 and march 2023 this package is a pure esm package. I made an example on how to use the module. Use version 1 for a commonjs version.

The result of this is that our current build is broken (silently according to our CI, due to #457)

I think we have three choices:

1. `service` should become esm / not transpile to cjs
2. we should use version 1 of mock-jwks
3. we should remove the mock-jwks dependency

**Comment by bickelj** [comment]
2
