### ISSUE TITLE
Model data ownership in the schema

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#485]
In order to "Add authorization" https://github.com/PhilanthropyDataCommons/service/issues/255 to the existing authentication scheme, more than a user with a JWT is required.

This task focuses on "the one who uploaded it can modify it exclusively" story.

In other words, this task can be considered complete without a full modeling of groups and inter-user or inter-group permissions (#484) when it is true that write access is no longer available except for the user (and perhaps associated groups, depending on whether this or #484 is completed first) that posted the data, for at least one entity.

**Comment by slifty** [comment]
This is related to the work in #396

**Comment by slifty** [comment]
I think that eventually we'll want to have a many:many relationship related to proposal "ownership"

That said, I also think there will only ever be a single "creator" (and that creator can be null)  even if we eventually want have more complex "owner" relationships.

For the purposes of our immediate use case I think creator is all we care about.

So with that in mind I'm going to add a `createdBy` attribute to the `bulk_uploads` and `proposals` table.  This would be a foreign key pointing to the `users` table.  This would then allow for the addition of a `createdBy` filter on `proposals` and `bulkUploads` that accepts a user reference, as well as a default narrowing of query results for any non-administrative user who hits those endpoints.

**Comment by slifty** [comment]
For a moment I was questioning whether we *actually* want to allow NULL for `createdBy` and right now I'm landing on "we do".

For instance, we may have internal scripts that populate proposals and are NOT associated with an authentication context.

The alternative, however, is that maybe we do want to require `createdBy` and we also want a system `user` that any internal system operations use when creating proposals / bulk uploads.

If we want to have a system user, we should think about whether (A) that should be a configured value via `.env` or (B) that should be a hard coded value.  I would probably lean towards a configurable value, though then we'll need to figure out how to create a dynamic migrations to create that user based on the env value, and if that value ever changes, things get weird...

I suppose I should sleep on this.

**Comment by bickelj** [comment]
I'm late to the party, but I think we do always want a "createdBy" user, it should be non-null. And I see that is the case in the `bulk_uploads` table, great!
