### ISSUE TITLE
Apply authorization modeling to relevant entities/endpoints

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#487]
Following #484, #485, and #486, which could be considered complete when there is one example of them, this task is to go back and make sure all the modeling done in those tasks is applied to the relevant entities. For example, if it only was applied to a handful of proposal endpoints, then we need to make sure it gets applied to any new endpoints that come about for organization, etc.

**Comment by slifty** [comment]
This issue is a necessary step however it's also very broad without knowing the specific use cases we are working to address.  I'm going to close it, but it will be a natural part of the implementation of certain features (e.g. #769)
