### ISSUE TITLE
Experiment with 3rd-party SSO login

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#492]
We want to allow partner organizations - or at least, one in particular - to be able to sign in to the PDC by signing in to their existing SSO. Keycloak supports this type of functionality: [Integrating identity providers](https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker).

Try to set up this kind of delegation in a test environment to make sure we understand how it works and that it will give us the user information we need.

We have an Office365 instance we can test with. MacArthur is using Okta for their SSO. We could also try starting with another Keycloak instance, if that's easier - I think the focus is more on `auth.pdco` than on the delegated-to identity provider.

**Comment by jasonaowen** [comment]
After discussing this further today, we decided that this model of user management is not something we'll do in Phase II. We might want to reopen this in Phase III, if a partner foundation requests this level of integration, but we have no such requests at this time.

(cc @kfogel)

**Comment by kfogel** [comment]
Re-closing as "not planned" rather than as "completed".

**Comment by kfogel** [comment]
We might change this from Wontfix to "might actually do" later on, but for now we have no compelling reason to implement this, so Wontfix is the right place.
