### ISSUE TITLE
Identify pilot-only data that needs scrubbing from the PDC

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#525]
~Before we can [redirect `pilot` to `app`](https://github.com/PhilanthropyDataCommons/front-end/issues/333) — effectively taking us out of pilot/beta — @jmergy notes that we should remove any data from the PDC that pilot participants only intended to be in the pilot.~ See comment below, this task is still important but not a blocker.

@jmergy and @jim-mcgowan will assess, identify any data that needs scrubbing, and then assign it if so.

**Comment by reefdog** [comment]
Bah! Why can't I assign @jmergy to this? And why doesn't his name autofill as I'm typing it, like others?

**Comment by slifty** [comment]
I don't think he's part of this organization!  I'll add him now.

**Comment by reefdog** [comment]
Per our 2023-10-11 meeting, @jim-mcgowan noted we don't actually need to wait to redirect `pilot` to `app` until this is decided. So it's no longer a blocker for that.
