### ISSUE TITLE
Set up a queue / processing system for handling bulk proposal uploads

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#559]
We want a system for processing bulk uploads (and probably other types of async processing over time, but this issue is focused on the immediate need).

**Comment by slifty** [comment]
The first step is picking a queue system.  Some options:

* **[BullMQ](https://www.npmjs.com/package/bullmq)** is queue / messaging system that uses Redis.  I've worked with [in the past](https://github.com/TechAndCheck/tech-and-check-alerts/tree/main) and I remember it being straightforward and clean.
* **[RabbitMQ](https://www.rabbitmq.com)** is also a thing, and the node client is [ampqplib](https://www.npmjs.com/package/amqplib).

Both seem to be well maintained; Rabbit seems like it might be a little heavier?  My inclination would be to use Bull.

**Comment by reefdog** [comment]
I recall Bull working well for us on T&C, and BullMQ being the modern/TS implementation speaks well. I say go forth!

**Comment by bickelj** [comment]
Copying my [comments from yesterday](https://chat.opentechstrategies.com/#narrow/stream/75-PDC/topic/queues/near/177528) here where I probably should have made them:

No strong feelings other than wondering if there's a way to avoid yet another dependency on another running process somewhere. Redis-based stuff or RabbitMQ sound fine to me if we need one though. IIRC it was easy to set up (rolling window) persistence with Redis. I don't think I tried persistence with RabbitMQ.

I have also seen Postgres (ab)used as a queue system. That's one way to avoid an additional dep but is worse than just using a Q system.

**Comment by bickelj** [comment]
If we assume a single back-end service instance, couldn't we use a TS or JS queue implementation? Like [this](https://www.npmjs.com/package/queue) or some other, better library that allows a redis backend optionally when it is finally needed (i.e. when we go to multiple back-end service instances)?

I'm not trying to be an obstacle, just asking because I don't know. From a distant, skimming observer view, "we need redis because file uploads" sounded like overkill. But this is bulk uploads so I may be way off and not understanding properly. Also, redis is great, so yea redis!

**Comment by slifty** [comment]
I spent some time today exploring non-redis approaches which also led me to step back and reflect on whether a queue is what we want.  Some alternatives I could think of were:

1. Hot folders
2. synchronous processing
3. cron jobs (looking database rows)

I think 1 and 2 are non-starters and would too easily result in brittleness / lost work.
I think 3 would have some non-functional impacts (e.g. jobs would sit unprocessed between cron runs, scaling would be harder to implement).

so queue still seems good!

---

@bickelj great find -- I think that's going to make sense for this stage of the project (if we need more scale / etc down the line it will be possible to migrate to something like BullMQ)

**Comment by bickelj** [comment]
@slifty It's OK either way. The downside of having it in the backend it is now we have a bunch of state in that one TS instance, nowhere persisted, such that it doesn't survive reboots, etc. But agree that it can get us started.

**Comment by slifty** [comment]
darn, looks like queue is ESM only, as described in https://github.com/jessetane/queue/issues/86#issuecomment-1375333009

So I think we're either locked into an old version (which might be fine?) or back to BullMQ.

**Comment by slifty** [comment]
After speaking with @jasonaowen today and I dug in a bit to explore psql based queues -- first, this thread has some interesting discussions: https://news.ycombinator.com/item?id=35526846

It sounds like psql is probably a Just Fine Approach given our needs in this project for the foreseeable future.

It looks like [pg-boss](https://www.npmjs.com/package/pg-boss) is a potential library for this, but I'll keep looking at the landscape.

**Comment by jasonaowen** [comment]
@slifty and I talked about this more during yesterday's dev meeting, and [reaffirmed what he wrote Tuesday](https://github.com/PhilanthropyDataCommons/service/issues/559#issuecomment-1799911890). The only thing to add is that the other package I found is [graphile-worker](https://www.npmjs.com/package/graphile-worker) - I haven't dug deeply into either, and both appear to suit our needs. I'll trust @slifty to decide which to use (or find a third option)!

**Comment by bickelj** [comment]
From https://www.prequel.co/blog/sql-maxis-why-we-ditched-rabbitmq-and-replaced-it-with-a-postgres-queue

> But there was seemingly no way to _actually_ set the prefetch count to zero (ie disable prefetching).

I'm skeptical that they interpreted this correctly. I think if you are using acks and set the prefetch to 1 I think RabbitMQ will "do the right thing."

That said, they're not wrong that there are advantages to maintaining one thing rather than two things, advantages to using a persistent transaction-based tool, and advantages to simpler code.

**Comment by slifty** [comment]
I looked a bit and it does seem that both pg-boss and graphile-worker suit our needs technically.

Both projects are primarily developed by single developers. That said, I get the sense that graphile-worker is a bit more robust in terms of community management (and is associated with a larger "project" [Graphile](https://github.com/graphile)).  The graphile dev bills appears to manage the graphile suite as a paid responsibility.

For that reason I'm gonna move forward with graphile-worker as the first path to walk down.
