### ISSUE TITLE
Base Field review: 'Organization Location'

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#603]
From https://github.com/PhilanthropyDataCommons/service/pull/305#discussion_r1172291408.
@jasonaowen:
> What is the intention of this field? Is this an address? If so, can we include the word address in the label and short code?

@bickelj:
> Here's the information I have on this one:
> >  Concatenated field that displays city/state for US orgs and city for non-US based orgs | This is a field that displays the city/state for US orgs and country for non-US orgs

@jasonaowen:
> That sounds duplicative of the existing organization_{city,state_province,country} fields; can we give the feedback that those should be used instead?

**Comment by bickelj** [comment]
Also consider 'Organization Latitude EPSG:4326' and 'Organization Longitude EPSG:4326'. See

**Comment by slifty** [comment]
At this point base field management is a user task (though we haven't written interfaces for it).

Which is just to say I'll close this as a developer task.  If the PDC governance team wants us to change base fields in the prod database we can make the appropriate API calls at that point!
