### ISSUE TITLE
Base Field review: 'Proposal Fiscal Sponsor Contact Last Name'

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#604]
From https://github.com/PhilanthropyDataCommons/service/pull/305#pullrequestreview-1393532584:

@jasonaowen:
> If we're changing this field, can we also combine it into a single name field instead of split first/last name fields?

@bickelj:
> I agree this still needs to be done. It will need to be in another change.

The old PR still needs to be merged but this issue is to avoid dropping that suggestion on the floor.

**Comment by slifty** [comment]
At this point base field management is a user task (though we haven't written interfaces for it).

Which is just to say I'll close this as a developer task.  If the PDC governance team wants us to change base fields in the prod database we can make the appropriate API calls at that point!
