### ISSUE TITLE
Base Field review: 'Updated Contact Information'

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#606]
From https://github.com/PhilanthropyDataCommons/service/pull/305#discussion_r1173132974.

@jasonaowen:
> What is the intent of this field? Is this handled by versioning in the PDC?

@bickelj:
> I was kind of puzzled by this one too. The best description I have is this:
> > Description of the changes the grant applicant would like made to their own contact information in the Foundation's database

**Comment by slifty** [comment]
At this point base field management is a user task (though we haven't written interfaces for it).

Which is just to say I'll close this as a developer task.  If the PDC governance team wants us to change base fields in the prod database we can make the appropriate API calls at that point!
