### ISSUE TITLE
Base Field review: 'Proposal Additional Contact Name'

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/service#607]
From https://github.com/PhilanthropyDataCommons/service/pull/305#pullrequestreview-1393532584

@jasonaowen:
> We can encode multiple values for a single field; does this need to be separate from proposal_primary_contact_name?
> Alternatively, do we also need the proposal_additional_contact_{title,phone,email} fields?

@bickelj:
> Another good call. It is past time to figure out a way to encode these many-to-one and one-to-many relationships in our base fields spreadsheet.
> We've made some strides toward figuring out these relationships, I think the issues that capture them are likely https://github.com/PhilanthropyDataCommons/service/issues/396 and https://github.com/PhilanthropyDataCommons/service/issues/333.

**Comment by slifty** [comment]
We decided that base field management and review should fall on the PDC governance team rather than being dev tasks.  Closing this issue here, though obviously we can make the appropriate API calls if any changes are requested!
