### ISSUE TITLE
Consider finding a new tool for migrations

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#609]
https://github.com/ThomWright/postgres-migrations seems to be a dead project.  I have a PR to fix a bug that affects us which has been open for about 18 months: https://github.com/ThomWright/postgres-migrations/pull/93

It also is not being kept up to date more generally / the last commit was made 2 years ago.

We might consider:

1. Forking, merging the fix, and publishing on our own.
2. Finding a different migration tool.

**Comment by slifty** [comment]
I opened https://github.com/ThomWright/postgres-migrations/issues/108 just in case there's a chance we can help maintain upstream (which I think would be explicitly better than forking and maintaining our own version).

**Comment by bickelj** [comment]
I have no objection to forking if you don't hear back soon. I guess the downside is integrating the fork, right? Either having to publish a newly-named fork to `npm` or to use a different integration mechanism from `npm` for this one library?

**Comment by jasonaowen** [comment]
Darn, that is limiting!

A third option would be to explore the [forks](https://github.com/ThomWright/postgres-migrations/network), and perhaps collaborate / contribute there. It looks like the [`@dzangolab/postgres-migrations`](https://github.com/dzangolab/postgres-migrations) repo has published to [npm](https://www.npmjs.com/package/@dzangolab/postgres-migrations), and the [zakpatterson/postgres-schema-migrations](https://github.com/zakpatterson/postgres-schema-migrations) repo has a schema fix but is not (obviously?) on npm.

**Comment by slifty** [comment]
zakpatterson's library is probably a good bet -- and they also did respond to the original issue pointing out that they had a fork.  I'm fine with it; I suppose the only real risk is that it might not be maintained in future... which is already the current state!  I'll try making the swap today.  If upstream ends up being interested in help maintaining we can cross that bridge (and I suspect zakpatterson might even be interested in joining that team)
