### ISSUE TITLE
Add `description` attribute to base fields

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#612]
We would like to be able to provide descriptions for base fields that instruct users what sort of data we expect to go there. These should be optional.

**Comment by slifty** [comment]
Moving this from blocked to todo.  We talked in zulip but I'd suggest that we shouldn't mark an issue as blocked simply because it has a sequence dependency (also I don't know if that actually is a dependency FWIW; we can / should add the table column without knowing the values)

**Comment by reefdog** [comment]
> (also I don't know if that actually is a dependency FWIW; we can / should add the table column without knowing the values)

Oh! I thought Jim said the whole concept of base field descriptions — not just their content — was dependent on a discussion you and he were going to have. If that's not the case, then this whole discussion was (almost) moot! (I mean, I still would have marked things `Blocked` if they couldn't be worked on due to unmet prerequisites, but this wouldn't have qualified.)

**Comment by slifty** [comment]
Huh, I must have missed that -- I think descriptions are an important part of the system design since over time without descriptions we're going to have a hard time deduplicating base fields without being able to know what the intention of a given field is.

**Comment by jim-mcgowan** [comment]
@reefdog The content of the descriptions is dependent on a conversation but not their creation . . .

**Comment by reefdog** [comment]
@jim-mcgowan @slifty Makes sense! Apologies for misunderstanding.
