### ISSUE TITLE
Write base field descriptions

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#613]
Once base fields support descriptions (see #612), we need to write them so users know what sort of data to provide for each field.

I'm assigning this to @jim-mcgowan but feel free to reassign to the unlucky wordsmith of your choice.

(Presumably there is a prerequisite task of someone with database or API access generating a list of base fields and labels, and loading them into an author-friendly interface like Google Sheets. @jim-mcgowan to request that from the data team when he's ready.)

**Comment by slifty** [comment]
Here's a list of base fields and descriptions https://docs.google.com/spreadsheets/d/1Bjd0vwHPERSeKXFlV2YG5d1robb6xoocaKAyYlV_fto/edit#gid=0

**Comment by reefdog** [comment]
Open question: since not all base fields have descriptions, on the Bulk Upload page where we render the table of base fields, do we:

1. Sort those with descriptions to the top of the table, or
2. Hide those without descriptions? (If this, we would need to change the copy above the table to qualify this.)
