### ISSUE TITLE
Question about formatting of hyphen in field label.

### ISSUE THREAD

**Issue by kfogel** [PhilanthropyDataCommons/service#634]
In...

https://github.com/PhilanthropyDataCommons/service/blob/ce8fabaa18bf26637126a37accec5d5a3fed8c95/src/database/seeds/0001-insert-base_fields.sql#L261

...is the leftmost field something we get from an external source and therefore must be left as-is verbatim?  I just happened to notice (when Dan was screen-sharing during our meeting just now) that the hyphen is jammed up against the "s" at the end of "metrics", whereas on other lines we have a space on both sides of similarly-situation hyphens in that leftmost field.

**Comment by slifty** [comment]
FWIW -- I don't really think that we should be including this base field in the first place!

**Comment by kfogel** [comment]
Ooomph, I hadn't meant to raise *that* question!  But okay -- er, class, discuss (I guess).

**Comment by slifty** [comment]
@kfogel actually, even more broadly our current list of base fields is obsolete / should be essentially thrown out and replaced with a smaller more curated set (see #561 for the start of this thinking).

Which is to say... there are some open issues around resolving this (and some of that conversation does potentially overlap a bit with #396)

The question for *this* issue is whether we should spend time worrying about typos in doomed data that doesn't really belong in the repository anyway 😅 (I'd suggest probably not!)

**Comment by kfogel** [comment]
@slifty No, no -- if that particular label is doomed anyway, then IMHO we can close this issue and be on our merry way, or, uh, whatever flavor of way we were to be on.
