### ISSUE TITLE
Remove dotenv

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#640]
Currently we're using [dotenv](https://www.npmjs.com/package/dotenv) to load environment variables from a `.env` file. This is primarily beneficial to developers, as in production we use actual environment variables.

Unfortunately, it has some complications (#59):

https://github.com/PhilanthropyDataCommons/service/blob/b4edf0d8e97b1ca172033cb7b0f8c06d7667f4bd/src/logger.ts#L7-L12

As discussed in https://github.com/PhilanthropyDataCommons/service/pull/635#discussion_r1408556444, I am increasingly of the opinion that such convenience support for developers should not live in the repo, but rather be the responsibility of the devs, via [direnv](https://direnv.net/), sourcing a `.env` file in the shell, or another way of managing environment variables. In that conversation, @slifty agreed, and we didn't want that to be forgotten despite being out-of-scope for that PR.

**Comment by slifty** [comment]
I'm gonna work on this now since it's very slightly peripheral to #568 and thinking about test logging settings will be simpler if I'm not also thinking about when / where / how dotenv should be invoked.
