### ISSUE TITLE
Store file size of bulk uploads

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/service#651]
Currently, the file size of bulk upload CSVs is not stored in the database. That information temporarily lives in the presigned `POST` request/response, and permanently lives in S3 as object metadata, but neither of those are immediately available to the API during `GET  /bulkUploads` request handling, and we want to display this information in the front-end.

Save the size of the file in the database so that we can return it to the front-end.

Via a PR review conversation: https://github.com/PhilanthropyDataCommons/front-end/pull/443#discussion_r1412903016

**Comment by jasonaowen** [comment]
I think the size will have to be populated via the worker, as I don't think we want to reach out to S3 *during* the register-bulk-upload API call. We could have the client pass the size in to the API and confirm/overwrite that during the job.

**Comment by slifty** [comment]
whoops missed this and worked on #697

this is covered now!
