### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#675]
From the recent `graphile-worker` dependabot PR:

> As of 24th October 2023, Node 20 is the active LTS and Node 18 is maintainence LTS

Is there a reason we should avoid updating?

**Comment by slifty** [comment]
Realizing this might be easier to do after completing #622 -- I may wait to take it on until then.

**Comment by jasonaowen** [comment]
Yeah, I think the only reason to avoid/defer uploading is because of the associated infra work - it should be easier as a DO App!

**Comment by bickelj** [comment]
Does DO separate the node version from the codebase? Of course that would be easier but with its own costs.

**Comment by bickelj** [comment]
(See #833 discussion)

I just tried running `npm ci` and `npm run build` using node 18, then did `npm run migrate` and `npm run start` and all seemed OK. I'll update node to 20 in the `deploy` repo (runtime) and then @slifty volunteered to update it here in the `service` repo (build time).

**Comment by bickelj** [comment]
@slifty OK, first pass is in PR #837 but I may have missed some spots or it may fail, I hereby leave that branch to thee!

**Comment by slifty** [comment]
This is complete 🎉
