### ISSUE TITLE
Create "Update" base field API endpoint

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#677]
As we add descriptions to the base fields we would like to start to move away from the idea of "seeds" for managing base field state (base fields are generally intended to be user driven, not code driven).  One step in that direction is to create the ability to edit a base field.

Once access control is implemented there will be some nuances to consider around what aspects of a base field can be updated and by who; for this initial implementation I don't think that needs to be addressed.

**Comment by reefdog** [comment]
Will only the description be editable, or will the label be editable as well?

**Comment by slifty** [comment]
The endpoint allows editing of *every* field (other than createdAt and id), so that's up to you!  I'd suggest just description and label being editable for now, though we might want to consider short code too (and make sure our admins know the impact of editing a short code).
