### ISSUE TITLE
What about opportunities with "Additional Forms"?

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#69]
There are cases where a given opportunity accept different application data at different times or based on different people.

Our schema right now does not directly support this use case but I wanted to capture it.

**Comment by bickelj** [comment]
Even though the multiple versions of an application form is designed for a different use case (keeping proposals pinned to their actual forms at the time of submission), the existing design might help satisfy this use case.

**Comment by slifty** [comment]
Closing as stale
