### ISSUE TITLE
Model users in the schema

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#710]
How do we represent users (and data ownership) in the PDC?
Do we need to consider organizations / user groups at this stage?

**Comment by slifty** [comment]
Our first implementation does not need to support the concept of user groups, since we are just focused on the following user stories:

1. Admin / superuser (this is basically the current "logged in" experience, which has full access to all data and endpoints)
2. Standard user (this is a new kind of user, that can only view proposal data associated with their account OR proposal data that is public)
3. Public user (this is not a new user since obviously there is a logged out state, but we'll be expanding what this kind of user can do).

This issue is about modeling so I'm gonna hone in on that.

Authentication is done by keycloak and results in a jwt, which is then parsed.  First step is going to be to better understand how much of that we need to keep track of in our ERD.  For instance, maybe the concept of "administrator" should be a keycloack concept rather than a PDC concept, maybe not!

**Comment by slifty** [comment]
It looks like these are the values associated with a jwt: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1

It looks like "subject" is the "principal" which, as I understand it, means the user.

There is a question about whether the jwt should include the *roles* of the user, and that is explored here: https://stackoverflow.com/questions/47224931/is-setting-roles-in-jwt-a-best-practice

I'm thinking we should only us the jwt for identifying the user, rather than identifying the user's roles.  For instance if someone had a role when the JWT was created then it wouldn't be possible to remove that role until that JWT expired.

This means for a given token / user we'll need to look up their role. It's possible we could look up the role from keycloak directly, but it feels cleaner (and fewer network requests) to just look that information up from the database / schema.

For that reason I'm leaning towards *not* using on keycloak for defining  roles within the PDC, and instead we would have a user table with a "superuser" flag.

**Comment by reefdog** [comment]
> It looks like "subject" is the "principal" which, as I understand it, means the user. …

@slifty Don't miss @jasonaowen's breakdown of relevant terms back in https://github.com/PhilanthropyDataCommons/service/issues/255#issuecomment-1468872874! (Which doesn't change what you wrote, I just want to be sure you have that useful reference handy.)

**Comment by slifty** [comment]
I'm planning to *not* have REST endpoints for users in this first implementation, but instead will update our express middleware that handles jwts so that they create / select the user associated with the JWT.

We may some day want a more RESTful user interaction, but for now it's an internal concept.
