### ISSUE TITLE
Change default port to 3001

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#740]
If the user doesn't configure a port in their env vars, the default port is 3000:

https://github.com/PhilanthropyDataCommons/service/blob/28cad21f13c9dcd8886eadf0185638c7835e0dae/src/index.ts#L10

This happens to also be the default port for firing up the front end, which means out of the box our two projects can't be run alongside each other. While this is obviously solvable through configuration, I think our defaults should be more cooperative.

Can we change this to 3001?

**Comment by slifty** [comment]
Ahem - well ACTUALLY the service came first, so, if you ask *me* it is YOU people who should update your port.

(jokes aside I have no actual opinions feel free to spin up a PR to update the port here!)

**Comment by reefdog** [comment]
lolsies. Well so I believe we're running on the default port for whatever built-in server `creat-react-app` chooses. So we're using platform defaults, whereas you made a CHOICE!!

**Comment by reefdog** [comment]
(I'll open a PR.)
