### ISSUE TITLE
Implement validation mechanism

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#760]
The service layer should perform validation on the field values of uploaded proposals. The database should be altered to assign a type to each base field, chosen from a set such as an enumerator, and related proposal field values should be validated against this type in the service layer. It can begin by validating the simple types of 'string', 'number', 'phone number', 'email', 'URL' and 'boolean'

**Comment by hminsky2002** [comment]
@slifty Should we change this issue to encapsulate the introduction of validation across fields as we discussed earlier today, or should we create a new issue to capture that?

**Comment by slifty** [comment]
@hminsky2002 Either is fine -- I guess just one issue to capture phone, number, email, and url fields is reasonable.

**Comment by bickelj** [comment]
Duplicate of #308
