### ISSUE TITLE
Discuss: Data ownership and visibility

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#770]
As we add the concept of "ownership" to data, we also need to clarify when this ownership affects visibility and access.

For instance: we will associate a bulk upload to the user who uploaded it (#758). However, does that mean we implicitly scope requests to `/bulkUpload` to only return data owned by the requesting user? If so, how do privileged users (e.g. admins) view all bulk uploads? For `/proposals`, normal users should be able to view everything (currently), so that endpoint shouldn't be scoped by requesting user; but then to support a "my proposals" view, do we add filtering by owner? Is that handled client-side only?

We should discuss and capture the discussion here.

**Comment by reefdog** [comment]
My suggestion:

By default, we should return the maximum scope of data authorized to the current user. It's fine if certain endpoints (e.g., `/bulkUploads`) have implicit permission scopes — e.g., when an admin hits it, they get all uploads, while a normal user only gets "their" uploads.

Further filtering by data owner (e.g., for "my proposals" or even "my bulk uploads [for an admin user]") should be opt-in. This can either be supported by filter parameters by the API, or by data-filtering by the client; I'd like the API to support it, but client filtering is a fine MVP.

**Comment by slifty** [comment]
That suggestion is fine with me, and makes intuitive sense -- and supporting the ability to filter (by uploader, or by anything else) would be a future feature.

**Comment by reefdog** [comment]
Okay cool! I thought we'd have to have more discussion, but if that's a coherent and comprehensive starting point, and actionable for you as the API provider to implement, we can close this! (I assigned to you because I figured you'd be the best judge of when we'd defined the rules sufficiently.)

**Comment by slifty** [comment]
I mean I only read the first two words of your idea and just assumed from there that you were saying what I had in mind so hold on let me re-read if you're gonna make it sound so officially determined!
