### ISSUE TITLE
Update our swagger spec

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#79]
I mistakenly wasn't updating the swagger spec as I defined new endpoints!

The canonicalFields endpoints should be added in, along with populated schema information.

**Comment by bickelj** [comment]
While poking at this, I found the same thing @slifty did here: https://github.com/ajv-validator/ajv/issues/1814#issuecomment-1239574448

**Comment by slifty** [comment]
@bickelj I did a bad thing and didn't link to this issue in a bunch of documentation I created :( -- sorry for the redundant effort; check out this branch to see if there's anything useful in there: https://github.com/PhilanthropyDataCommons/service/blob/noissue-september-demo-lock/src/openapi.json

**Comment by bickelj** [comment]
@slifty Nice, I pushed that version instead.

**Comment by slifty** [comment]
I think this is finished now (we still need to keep it up to date but I believe the current state reflects current implementation)
