### ISSUE TITLE
Set up schema

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#8]
Now that #2 is resolved it's time to implement our schema.

One nice pattern I've seen used is to use [tinypg](https://www.npmjs.com/package/tinypg) as an alternative to a full blown ORM, along with very simple SQL based migrations.  I think that suits our needs for this project well; we can always get more complex later if we want to, but this approach is very explicit and still has the benefits of sanitization and structured migration.

Here's an example project that uses this pattern: https://gitlab.com/dial/principles/sustainability-toolkit-api/-/tree/development/src/database

**Comment by slifty** [comment]
This is complete -- tinypg and postgres-migrations are part of the project!

**Comment by bickelj** [comment]
My interpretation of the issue being open and there being no schema in the codebase was that the schema is still needed, but I agree with the direction of implementing the parts of the schema needed when it is needed, which I guess we might have discussed elsewhere and agreed to. Regardless, PR #29 is focused on the two most important endpoints `applications` and `opportunities`.

**Comment by slifty** [comment]
Right!  I think that implementing the full schema was probably a poorly scoped issue (my bad; I opened it) -- but *supporting* the ability to develop the schema as we add features is a good way to go.

So really this issue should have been "set up database and schema definition patterns"
