### ISSUE TITLE
Change our query approach to use DB-level json functions

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#821]
A long time ago we had a big conversation about the best way to load deep objects from postgres (e.g. when loading a proposal, also load the versions / field values).  We punted on the implementation of our selected path due to priorities in the moment, but as I start working on the new `Organization` / `Proposals` relationship (#799) I would like to finally shave that yak.

I'm making a separate issue for this, as it will impact essentially every endpoint / query and I think it's functionally a prerequisite to proper implementation of #799 

The idea will be to create a series of `foo_to_json` functions in postgres which will return json for a given entity directly (and therefore be able to also query / populate the nested object structures as well since it won't be returned as a traditional row-based result set).

**Comment by bickelj** [comment]
@slifty I think this is pretty much done, yes? If not, reopen.
