### ISSUE TITLE
Update to OpenAPI 3.1

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#849]
Swagger supports OpenApi 3.1 (we're using 3.0 right now)

* https://swagger.io/blog/swagger-supports-openapi-3-1/
* https://dev.to/mikeralphson/openapi-31-the-gnarly-bits-58d0

I believe we should upgrade so we can use the latest features of the spec.

**Comment by slifty** [comment]
It looks like this might have to get put on ice due to the fact that swagger-codegen doesn't seem to support OAS 3.1 yet: https://github.com/swagger-api/swagger-codegen/issues/12210

**Comment by reefdog** [comment]
Oof. @slifty Do you want to keep a running list here of the impact of 3.0 to us? I know of the need for the `readOnly` hack, and the resulting flattening of child objects. (Though each of those could probably use your more-accurate descriptions.) Anything else?

**Comment by slifty** [comment]
Pretty much just that -- basically, 3.1 made the concept of inheritance a bit more natural in the spec.  It's not a major issue beyond just "it would be good to use the latest version of the specification"
