### ISSUE TITLE
Run CI on PRs that are opened against non-main branches

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#897]
Sometimes you need to open a PR that includes commits in another PR that has not yet been merged to main.  When this happens it can be helpful to mark the base branch as the OTHER branch, rather than main.

Unfortunately our CI rules will not run against those PRs since they have some rules around main branch:

```
  pull_request:
    branches: [main]
```

I don't think that requirement is actually needed; let's take it out to improve our quality of life!

**Comment by reefdog** [comment]
@slifty This can be closed, right? It was resolved by #898 but it looks like you mentioned the wrong issue in the PR desc so it didn't close automatically.
