### ISSUE TITLE
Add a "pdc-admin" group to keycloak + instructions for setup in README

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#907]

**Comment by bickelj** [comment]
I added the `pdc-admin` group to both test and prod. I also added @slifty to the group, so @slifty your JWT should reflect that somehow.

**Comment by slifty** [comment]
@bickelj hmm, it looks like we actually need to add a `role` for this as well in order for it to show up in the jwt!

**Comment by bickelj** [comment]
@slifty Corrected and additional PR #919 added!

**Comment by slifty** [comment]
Woohoo!  and with that I *think* this issue can be closed!

**Comment by bickelj** [comment]
@slifty @reefdog I think there might be a loose end here that I can tie off. Shouldn't members of `pdc-admin` gain access to the Keycloak interface to manage users in the PDC realm as well, e.g. via https://auth.philanthropydatacommons.org/admin/pdc/console?

**Comment by slifty** [comment]
@bickelj That's a fine question but I don't think it's directly related to the PDC administration intention of the group; I don't think we should couple that necessarily.  We might want to grant a user one read / write access to PDC without giving them auth admin access.

Either way: could you open a new issue to explore that question?

(In general I think it's best practice to create new issues that are more narrowly scoped to the new improvement (or bug) that's been identified with a reference to the original issue.  The initial issue *was* completed and closed so 99% of the initial scope is wrapped up!)
