### ISSUE TITLE
Organizations should have a `taxId` not an `employerIdentificationNumber`

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#931]
Our organizations have an `employerIdentificationNumber` attribute.  This was a naming mistake -- EIN is a [US-specific thing](https://en.wikipedia.org/wiki/Employer_Identification_Number) whereas `taxId` is a more generic term and is what they use over at https://schema.org/Organization

This isn't a huge issue, but I think would be worth cleaning up sooner than later since it would be a breaking change.

**Comment by slifty** [comment]
cc  @reefdog @hminsky2002 on this

**Comment by reefdog** [comment]
Agree and co-sign. This feels like a good thing to change before landing Phase 2, too.

**Comment by reefdog** [comment]
Do you think it's worth reframing this as a `federalId` or `governmentId` rather than _tax_ ID? (I grok that tax ID is the correct term of art but wonder if we should go with a sort of context agnosticism / semantic appropriateness.)

**Comment by slifty** [comment]
@reefdog ohhh I like `governmentId` plenty.  My only pause is that schema.org landing on `taxId` seems like a meaningful data point (since they're an entity that exists to think about this kind of thing).  @jmergy had mentioned others in the PDC ecosystem had brought up schema.org, and so especially as we start landing on "official" attributes it might make sense to try to defer to theirs unless we have a particular reason to divert.

**Comment by reefdog** [comment]
Ah, yeah, I’m down with taking hints from Schema.org. 👍

**Comment by jmergy** [comment]
@reefdog @slifty I do think schema dot org is a safe go-to. It has come up a few times in discussions around folks with data or not wanting to have PDC create more than necessary. There is a sense with some data that may be in play with PDC that schema dot org is something that is used as a guide in lieu of making things up. 

I could also see us publishing a schema back - perhaps on bulk upload or something to contribute...
