### ISSUE TITLE
Opportunity data fields for the MacArthur Foundation/Fluxx

### ISSUE THREAD

**Issue by jim-mcgowan** [PhilanthropyDataCommons/service#94]
Attached are the opportunity data fields for the MacArthur Foundation/Fluxx.<br>
[MacArthur Foundation-Fluxx Data Fields.xlsx](https://github.com/PhilanthropyDataCommons/service/files/9728067/MacArthur.Foundation-Fluxx.Data.Fields.xlsx)

**Comment by bickelj** [comment]
Thank you!

**Comment by bickelj** [comment]
Without objection, this can be considered part of #102
