### ISSUE TITLE
Migrations hang for several seconds at the end of the task

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/service#947]
After the last apparent step of `npm run migrate` (`[2024-04-22T22:15:05.486Z] INFO (15994): Migrations complete.`), the console seems to hang for several seconds before exiting back to the terminal prompt.

@slifty says this is likely a bug.

**Comment by slifty** [comment]
On second thought this is a mindfulness feature, and you should use that time to focus on your breathing.

**Comment by reefdog** [comment]
> On second thought this is a mindfulness feature, and you should use that time to focus on your breathing.

Real actual lol.
