### ISSUE TITLE
Opportunity data fields for the Miami Foundation/Submittable

### ISSUE THREAD

**Issue by jim-mcgowan** [PhilanthropyDataCommons/service#95]
Attached are the opportunity data fields for the Miami Foundation/Submittable.<br>
[Miami Foundation-Submittable Data Fields.xlsx](https://github.com/PhilanthropyDataCommons/service/files/9728072/Miami.Foundation-Submittable.Data.Fields.xlsx)

**Comment by bickelj** [comment]
Thank you!
