### ISSUE TITLE
Proposal data is "not found"

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/service#951]
I _think_ this might be broken. Locally:

Hitting `http://localhost:3001/proposals?_page=1&_count=100&organization=10` returns:
```json
{
  "entries": [
    {
      "id": 114,
      "versions": [...],
      "createdAt": "2024-04-19T16:32:58.714618-05:00",
      "createdBy": 5,
      "externalId": "2",
      "opportunityId": 54
    },
    {
      "id": 112,
      "versions": [...],
      "createdAt": "2024-04-19T16:32:54.533533-05:00",
      "createdBy": 5,
      "externalId": "2",
      "opportunityId": 53
    }
  ],
  "total": 110
}
```

But then hitting `http://localhost:3001/proposals/114` returns:
```json
{
  "name": "NotFoundError",
  "message": "The proposal was not found (id: 114)",
  "details": [
    {
      "name": "NotFoundError"
    }
  ]
}
```

_Originally posted by @reefdog in https://github.com/PhilanthropyDataCommons/service/issues/932#issuecomment-2071351538_

**Comment by reefdog** [comment]
@slifty This is a showstopping bug atm. Proposal detail pages, and proposal "side panel" pages on org pages — both of which are crucial — are currently broken.

**Comment by hminsky2002** [comment]
@reefdog @slifty 
What are the steps to reproduce this? On local, I'm running the latest main branch for front-end and service and am seeing expected behavior 
<img width="1674" alt="Screen Shot 2024-04-23 at 11 41 08 PM" src="https://github.com/PhilanthropyDataCommons/service/assets/18370464/74f54b87-9070-422a-ad6e-0d12d00b97bd">
with proposal pages 
<img width="1674" alt="Screen Shot 2024-04-23 at 11 41 14 PM" src="https://github.com/PhilanthropyDataCommons/service/assets/18370464/40999d98-fcf0-4ead-8d01-e349129b4c4d">
and organization detail pages,

and then (via swagger)
``` http://localhost:3001/proposals?_page=1&_count=100&organization=1 ```
returns 
```json
{
  "entries": [
    {
      "id": 1,
      "versions": [
        {
          "id": 1,
          "version": 1,
          "createdAt": "2024-04-15T12:13:11.851105-04:00",
          "proposalId": 1,
          "fieldValues": [
            {
              "id": 1,
              "value": "test1",
              "isValid": true,
              "position": 0,
              "createdAt": "2024-04-15T12:13:11.88021-04:00",
              "proposalVersionId": 1,
              "applicationFormField": {
               // etc
              },
              "applicationFormFieldId": 1
            },
           //etc etc
          ],
          "applicationFormId": 1
        }
      ],
      "createdAt": "2024-04-15T12:13:11.826575-04:00",
      "createdBy": 2,
      "externalId": "1",
      "opportunityId": 1
    }
  ],
  "total": 3
}
```

while ```http://localhost:3001/proposals/1```
returns
```json

Download
{
  "id": 1,
  "versions": [
    {
      "id": 1,
      "version": 1,
      "createdAt": "2024-04-15T12:13:11.851105-04:00",
      "proposalId": 1,
      "fieldValues": [
        {
          "id": 1,
          "value": "test1",
          "isValid": true,
          "position": 0,
          "createdAt": "2024-04-15T12:13:11.88021-04:00",
          "proposalVersionId": 1,
          "applicationFormField": {
          // etc
        },
        
  ],
  "createdAt": "2024-04-15T12:13:11.826575-04:00",
  "createdBy": 2,
  "externalId": "1",
  "opportunityId": 1
}
```

**Comment by reefdog** [comment]
@hminsky2002 I think the trick is you have to try to view a proposal that isn't yours.

**Comment by slifty** [comment]
@reefdog based on your response in the other thread I thought you were viewing a proposal you *did* own as an admin.  Is that the case or no?

**Comment by reefdog** [comment]
@slifty 🤦 You're right. Late night Justin was… confused. So this is even more weird then.
