### ISSUE TITLE
Fix seed file typo

### ISSUE THREAD

**Issue by hminsky2002** [PhilanthropyDataCommons/service#975]
I just noticed that when editing the seed file in [this commit](https://github.com/PhilanthropyDataCommons/service/commit/27d5e3c956e2e364dae51755e10db490c4dd1e7b), I accidentally typed some of the base fields that were supposed to be of type 'URL' as 'url.' This is a quick fix for those instances!

**Comment by slifty** [comment]
The irony is that we tend to not use upper case for things like `url` and so the enum is the thing that is not like the others.

I'm very minorly torn on whether we should fix that... cc @reefdog thoughts as an API user?

**Comment by reefdog** [comment]
@slifty Ah, I'm glad you asked! Yes, I would expect the value to be lowercase. At least, alongside the other enum values:

```ts
export enum BaseFieldDataType {
	STRING = 'string',
	NUMBER = 'number',
	PHONE_NUMBER = 'phone_number',
	EMAIL = 'email',
	URL = 'URL',
	BOOLEAN = 'boolean',
}
```

**Comment by slifty** [comment]
@hminsky2002 migrations aren't a dirty word -- I think we should still merge the fix, but then *sigh* -- let's go ahead and update the enum to match the rest of 'em.  Sorry I didn't catch this in the initial code review!
